// providers/pinyin.js
// Simple offline pinyin provider using a small built-in dictionary.
// For any characters not in the map, the original character is returned.

const MAP = {
  "你": "ni",
  "好": "hao",
  "世": "shi",
  "界": "jie",
  "中": "zhong",
  "文": "wen",
  "我": "wo",
  "是": "shi",
  "的": "de",
  "一": "yi",
  "不": "bu",
  "了": "le",
  "人": "ren",
  "在": "zai",
  "有": "you",
  "这": "zhe",
  "那": "na",
  "他": "ta",
  "她": "ta",
  "它": "ta",
  "们": "men",
  "和": "he",
  "爱": "ai",
  "国": "guo",
  "家": "jia",
  "学": "xue",
  "习": "xi",
  "生": "sheng",
  "工": "gong",
  "作": "zuo",
  "上": "shang",
  "下": "xia",
  "来": "lai",
  "去": "qu",
  "大": "da",
  "小": "xiao",
  "天": "tian",
  "地": "di",
  "说": "shuo",
  "话": "hua",
  "吃": "chi",
  "喝": "he",
  "看": "kan",
  "听": "ting",
  "走": "zou",
  "路": "lu",
  "吗": "ma",
  "什": "shen",
  "么": "me",
  "请": "qing",
  "谢": "xie",
  "对": "dui",
  "错": "cuo",
  "朋": "peng",
  "友": "you",
  "喜": "xi",
  "欢": "huan",
  "再": "zai",
  "见": "jian",
  "入": "ru",
  "口": "kou",
  "出": "chu",
  "多": "duo",
  "少": "shao",
  "买": "mai",
  "卖": "mai",
  "日": "ri",
  "月": "yue",
  "年": "nian",
  "时": "shi",
  "分": "fen",
  "先": "xian",
  "女": "nv",
  "儿": "er",
  "子": "zi",
  "妈": "ma",
  "爸": "ba",
  "老": "lao",
  "师": "shi",
  "书": "shu",
  "笔": "bi",
  "电": "dian",
  "东": "dong",
  "西": "xi",
  "南": "nan",
  "北": "bei",
  "水": "shui",
};

export async function translatePinyin(texts) {
  const arr = Array.isArray(texts) ? texts : [String(texts ?? "")];
  return arr.map(str => {
    const pinyin = Array.from(str).map(ch => MAP[ch] || ch).join(" ").trim();
    return { characters: str, pinyin };
  });
}

